version: "3.3"

services:
    app:
        build:
            context: ./Server
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            # - 4848:4848
           #- 9009:9009 # debug port
        depends_on:
            - db
            - zookeeper
            - kafka

    db:
        image: postgres:9.6.17
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - db-data:/var/lib/postgresql/data

    # kafka:
    #     image: spotify/kafka
    #     environment:
    #         ADVERTISED_HOST: "docker-machine ip \"docker-machine active\""
    #         ADVERTISED_PORT: 9092
    #     ports:
    #         - "9092:9092"
    #         - "2181:2181"

    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka:2.12-2.4.0
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on:
            - zookeeper
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    # web:
    #     build: ./web
    #     ports:
    #         - 80:80
    #     depends_on:
    #         - app
    #     volumes:
    #         - ./web # for develpment only

volumes:
    db-data:
