version: "3.7"

services:
    app:
        build:
            context: ./Server/stickmanCharades
            dockerfile: Dockerfile-prod
        ports:
            - 8080:8080
            - 4848:4848
           #- 9009:9009 # debug port
        depends_on:
            - db
            - kafka-zookeeper
            - kafka-broker

    db:
        image: postgres:9.6.17
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - db-data:/var/lib/postgresql/data

    kafka-zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
            - 2181:2181
    kafka-broker:
        image: wurstmeister/kafka:2.12-2.4.0
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
        depends_on:
            - kafka-zookeeper
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    web:
        build: ./web
        ports:
            - 80:80
        depends_on:
            - app
        volumes:
            - ./web # for develpment only

volumes:
    db-data:
